. .\functions.ps1

$Tasks = [ordered]@{
    "Computer umbenennen"={Rename-Computer -NewName $global:ComputerName}
    "Dateiendungen einblenden"={ShowKnownExtensions};
    "3D Objekte verstecken"={Hide3DObjectsFromExplorer};
    "Bloatware löschen (Skype)"={Uninstall-Bloat};
    "Fax entfernen"={RemoveFaxPrinter};
    "XPS entfernen"={UninstallXPSPrinter};
    "WiFi deaktivieren"={Disable-Wireless};
    "Bluetooth deaktivieren"={Disable-Bluetooth};
    "Drucker installieren"={Add-Printer -ConnectionName "\\druckerserver\toshiba" -Name "Toshiba"};
    "Standarddrucker setzen"={Set-DefaultPrinter -PrinterName "Toshiba"};
    "Druckerinstallation verbieten"={Disable-PrinterInstallation};
    "Windows Update deaktivieren"={Disable-WindowsUpdate};
    "Lockscreen deaktivieren"={DisableLockscreen};
    "Cortana abschalten"={DisableCortana};
    "Surfer erstellen"={Add-SurferUser};
    "Autologin aktivieren"={Enable-Autologin};
    "Remove and Block Edge"={Disable-MSEdge};
    "Searchbox entfernen"={Disable-SearchBox};
    "Taskview entfernen"={Disable-Taskview};
    #"Wallpaper ändern"={Set-WallPaper -Image ".\assets\wallpaper.jpg" -Style Fill};
    "News deaktivieren"={Disable-Feed};
    "VLC installieren"={Install-VLC};
    "Google Chrome installieren"={Install-GoogleChrome};
    "Google Chrome als Standard"={Set-DefaultBrowser};
    "Passwörter nicht Speichern in Chrome"={Disable-ChromePasswordManager};
    "Startseite im Browser"={Set-Homepage};
    "I don't care about cookies"={Install-IDontCareAboutCookies};
    "uBlock Origin"={Install-UblockOrigin};
    "Acrobat installieren"={choco install adobereader -params '"/UpdateMode 0"'};
    "Acrobat als Standard"={Set-DefaultPDFReader};
    "Office installieren"={Install-Office};
    "OneDrive Deinstallieren"={UninstallOneDrive};
    "7zip installieren"={Install-7zip};
    "ClassicShell (OpenShell) installieren"={Install-OpenShell};
    "Papercut installieren"={Install-Papercut};
    "DeepFreeze installieren"={Install-DeepFreeze};
    "Helper deinstallieren"={Uninstall-Helpers};
}